🌟 Exercise 1 : Array Creation and Manipulation
Instructions
Create a 1D NumPy array containing numbers from 0 to 9.

Expected Output:



array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [1]:
import numpy as np
ar = np.arange(0,10)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

 Exercise 2 : Type Conversion and Array Operations
Instructions
Convert a list [3.14, 2.17, 0, 1, 2] into a NumPy array and convert its data type to integer.

Expected Output:



array([3, 2, 0, 1, 2])

In [2]:
l = [3.14, 2.17, 0, 1, 2]
ar = np.array(l, dtype = int)
ar

array([3, 2, 0, 1, 2])

 Exercise 3 : Working with Multi-Dimensional Arrays
Instructions
Create a 3x3 NumPy array with values ranging from 1 to 9.

Expected Output:



array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
k = 0
ar = np.zeros((3, 3), dtype=int)
for i in range(3):
    for j in range(3):
        k += 1
        ar[i,j] = k
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

🌟 Exercise 4 : Creating Multi-Dimensional Array with Random Numbers
Instructions
Create a 2D NumPy array of shape (4, 5) filled with random numbers.

Expected Output:



array([[0.56, 0.85, 0.01, 0.42, 0.68],
       [0.22, 0.37, 0.73, 0.93, 0.39],
       [0.44, 0.03, 0.87, 0.02, 0.83],
       [0.78, 0.87, 0.98, 0.80, 0.46]])

In [15]:
np.random.seed(42)
ar = np.random.rand(4, 5)
ar

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864],
       [0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258],
       [0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497],
       [0.18340451, 0.30424224, 0.52475643, 0.43194502, 0.29122914]])

🌟 Exercise 5 : Indexing Arrays
Instructions
Select the second row from a given 2D NumPy array.

Expected Output:



array([20, 21, 22, 23, 24])

In [16]:
ar[1,:]

array([0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258])

🌟 Exercise 6 : Reversing elements
Instructions
Reverse the order of elements in a given 1D NumPy array (first element becomes last).

Expected Output:



array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [21]:
ar = np.arange(0,10)
print(ar[::-1])
print(ar)

[9 8 7 6 5 4 3 2 1 0]
[0 1 2 3 4 5 6 7 8 9]


🌟 Exercise 7 : Identity Matrix
Instructions
Create a 4x4 identity matrix using NumPy.

Expected Output:



array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
ar = np.eye(4)
ar

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

 Exercise 8 : Simple Aggregate Funcs
Instructions
Find the sum and average of a given 1D array.

Expected Output:



Sum: 45, Average: 4.5

In [40]:
np.random.seed(42)
ar = np.random.randint(10, 50, 6)
print(ar, ar.sum(), ar.mean())

[48 38 24 17 30 48] 205 34.166666666666664


Exercise 9 : Create Array and Change its Structure
Instructions
Create a NumPy array with elements from 1 to 20; then reshape it into a 4x5 matrix.

Expected Output:



array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [41]:
ar = np.zeros((5,4), dtype = int)
k = 0
for i in range(5):
    for j in range(4):
        k += 1
        ar[i,j] = k
ar

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

 Exercise 10 : Conditional Selection of Values
Instructions
Extract all odd numbers from a given NumPy array.

Expected Output:



array([1, 3, 5, 7, 9])

In [43]:
ar = np.arange(1,10)
ar[ar%2 == 1]

array([1, 3, 5, 7, 9])